name: Migrate & Deploy Backend (server)

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  migrate_and_deploy:
    name: Run DB migrations & Deploy (Railway v4)
    runs-on: ubuntu-latest
    environment: "Restaurant-Web-App (bountiful-celebration / production)"

    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}          # project token
      RAILWAY_SERVICE: "Restaurant-Web-App"                # your backend service name
      RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }} # optional
      DATABASE_URL: ${{ secrets.DB_URL }}
      NODE_ENV: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Debug - show versions (optional)
        run: |
          node -v
          npm -v
          railway --version || true

      - name: Run Sequelize migrations on Railway (remote)
        working-directory: ./server
        run: |
          echo ">>> Running migrations using railway run (service: $RAILWAY_SERVICE)"
          # v4 syntax — note the '--' separator for command arguments
          railway run --service "$RAILWAY_SERVICE" -- \
            npx sequelize-cli db:migrate --config config/config.cjs --migrations-path migrations

      - name: Deploy backend (server) to Railway
        working-directory: ./server
        run: |
          echo ">>> Deploying service $RAILWAY_SERVICE to Railway"
          # For v4 CLI: --service is supported, no need for --yes / --no-watch
          # '--detach' means deploy without tailing logs
          railway up --service "$RAILWAY_SERVICE" --detach
