name: Migrate & Deploy Backend on Railway

on:
  push:
    branches: [ master ]    
  workflow_dispatch:

jobs:
  migrate_and_deploy:
    runs-on: ubuntu-latest
    environment: "Restaurant-Web-App (bountiful-celebration / production)"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies (server)
        working-directory: ./server
        run: npm ci

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Login to Railway
        env:
          RAILWAY_API_KEY: ${{ secrets.RAILWAY_API_KEY }}
        run: echo $RAILWAY_API_KEY | railway login --token

      - name: Run migrations on Railway (remote)
        working-directory: ./server
        env:
          RAILWAY_API_KEY: ${{ secrets.RAILWAY_API_KEY }}
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
        run: |
          echo "Running migrations from Railway network..."
          railway run --project $RAILWAY_PROJECT_ID -- npx sequelize-cli db:migrate --config config/config.cjs --migrations-path migrations

      - name: Deploy backend (server folder) to Railway
        working-directory: ./server
        env:
          RAILWAY_API_KEY: ${{ secrets.RAILWAY_API_KEY }}
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
        run: |
          echo "Deploying server to Railway..."
          railway up --project $RAILWAY_PROJECT_ID --yes --no-watch
